Controllers/AgendamentoController.cs
using Bluetrip.Data;
using Bluetrip.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Bluetrip.Controllers;
public class AgendamentoController : Controller
{
    private readonly ApplicationDbContext _context;

    public AgendamentoController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        return View(_context.Agendamento.ToList());
    }

    public IActionResult Create()
    {
        ViewBag.Turistas = _context.Turista.ToList();
        ViewBag.Eventos = _context.Evento.ToList();

        return View();
    }

    [HttpPost]
    public IActionResult Create(AgendamentoModel agendamento)
    {
        try
        {
            _context.Agendamento.Add(agendamento);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            ViewBag.Turistas = _context.Turista.ToList();
            ViewBag.Eventos = _context.Evento.ToList();

            Debug.WriteLine(e.Message);
            return View(agendamento);
        }
    }

    public IActionResult Edit(int id)
    {
        var agendamento = _context.Agendamento.Find(id);

        if(agendamento == null)
        {
            return NotFound();
        }


        ViewBag.Turistas = _context.Turista.ToList();
        ViewBag.Eventos = _context.Evento.ToList();

        return View(agendamento);
    }

    [HttpPost]
    public IActionResult Edit(AgendamentoModel agendamento)
    {
        try
        {
            _context.Agendamento.Update(agendamento);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            ViewBag.Turistas = _context.Turista.ToList();
            ViewBag.Eventos = _context.Evento.ToList();

            Debug.WriteLine(e.Message);
            return View(agendamento);
        }
    }

    public IActionResult Delete(int id)
    {
        var agendamento = _context.Agendamento.Find(id);

        if(agendamento == null)
        {
            return NotFound();
        }

        return View(agendamento);
    }

    [HttpPost, ActionName("Delete")]
    public IActionResult DeleteConfirmed(int id)
    {
        var agendamento = _context.Agendamento.Find(id);

        if(agendamento == null)
        {
            return NotFound();
        }

        _context.Agendamento.Remove(agendamento);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }
}

Controllers/EventoController.cs
using Bluetrip.Data;
using Bluetrip.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bluetrip.Controllers;
public class EventoController : Controller
{
    private readonly ApplicationDbContext _context;

    public EventoController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        return View(_context.Evento.ToList());
    }

    public IActionResult Create()
    {
        ViewBag.PontosTuristicos = _context.PontoTuristico.ToList();

        return View();
    }

    [HttpPost]
    public IActionResult Create(EventoModel evento)
    {
        try
        {
            _context.Evento.Add(evento);
            _context.SaveChanges();
            return RedirectToAction("Index");
        } catch(Exception e)
        {
            ViewBag.PontosTuristicos = _context.PontoTuristico.ToList();

            Debug.WriteLine(e.Message);
            return View(evento);
        }
    }

    public IActionResult Edit(int id)
    {
        var evento = _context.Evento.Find(id);

        if(evento == null)
        {
            return NotFound();
        }

        ViewBag.PontosTuristicos = _context.PontoTuristico.ToList();

        return View(evento);
    }

    [HttpPost]
    public IActionResult Edit(EventoModel evento)
    {
        try
        {
            _context.Evento.Update(evento);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            ViewBag.PontosTuristicos = _context.PontoTuristico.ToList();

            Debug.WriteLine(e.Message);
            return View(evento);
        }
    }

    public IActionResult Delete(int id)
    {
        var evento = _context.Evento.Find(id);

        if(evento == null)
        {
            return NotFound();
        }

        return View(evento);
    }

    [HttpPost, ActionName("Delete")]
    public IActionResult DeleteConfirmed(int id)
    {
        var evento = _context.Evento.Find(id);

        if(evento == null)
        {
            return NotFound();
        }

        _context.Evento.Remove(evento);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }
}

Controllers/PontoTuristicoController.cs
using Bluetrip.Data;
using Bluetrip.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using System.Diagnostics;

namespace Bluetrip.Controllers;
public class PontoTuristicoController : Controller
{
    private readonly ApplicationDbContext _context;

    public PontoTuristicoController(ApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
        return View(await _context.PontoTuristico.Include(p => p.Endereco).ToListAsync());
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(PontoTuristicoModel pontoTuristico)
    {
        if (ModelState.IsValid)
        {
            var endereco = _context.Endereco.Add(pontoTuristico.Endereco);
            _context.SaveChanges();

            pontoTuristico.EnderecoId = endereco.Entity.EnderecoId;

            _context.PontoTuristico.Add(pontoTuristico);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        return View(pontoTuristico);
    }

    public IActionResult Edit(int id)
    {
        var pontoTuristico = _context.PontoTuristico.Include(p => p.Endereco).FirstOrDefault(p => p.PontoTuristicoId == id);

        if(pontoTuristico == null)
        {
            return NotFound();
        }

        return View(pontoTuristico);
    }

    [HttpPost]
    public IActionResult Edit(PontoTuristicoModel pontoTuristico)
    {
        if (ModelState.IsValid)
        {
            _context.Endereco.Update(pontoTuristico.Endereco);
            _context.PontoTuristico.Update(pontoTuristico);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        return View(pontoTuristico);
    }

    public IActionResult Delete(int id)
    {
        var pontoTuristico = _context.PontoTuristico.Find(id);

        if(pontoTuristico == null)
        {
            return NotFound();
        }

        return View(pontoTuristico);
    }

    [HttpPost, ActionName("Delete")]
    public IActionResult DeleteConfirmed(int id)
    {
        var pontoTuristico = _context.PontoTuristico.Find(id);

        if(pontoTuristico == null)
        {
            return NotFound();
        }

        _context.PontoTuristico.Remove(pontoTuristico);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }
}

Controllers/TuristaController.cs
using Bluetrip.Data;
using Bluetrip.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bluetrip.Controllers;
public class TuristaController : Controller
{
    private readonly ApplicationDbContext _context;

    public TuristaController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        return View(_context.Turista.ToList());
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(TuristaModel turista)
    {
        if (ModelState.IsValid)
        {
            _context.Turista.Add(turista);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        return View(turista);
    }

    public IActionResult Edit(int id)
    {
        var turista = _context.Turista.Find(id);

        if(turista == null)
        {
            return NotFound();
        }

        return View(turista);
    }

    [HttpPost]
    public IActionResult Edit(TuristaModel turista)
    {
        if (ModelState.IsValid)
        {
            _context.Turista.Update(turista);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        return View(turista);
    }

    public IActionResult Delete(int id)
    {
        var turista = _context.Turista.Find(id);

        if(turista == null)
        {
            return NotFound();
        }

        return View(turista);
    }

    [HttpPost, ActionName("Delete")]
    public IActionResult DeleteConfirmed(int id)
    {
        var turista = _context.Turista.Find(id);

        if(turista == null)
        {
            return NotFound();
        }

        _context.Turista.Remove(turista);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bluetrip</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bluetrip.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/logo.svg" alt="Bluetrip" style="height: 48px;"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PontoTuristico" asp-action="Index">Pontos Turísticos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Evento" asp-action="Index">Eventos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Turista" asp-action="Index">Turistas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Agendamento" asp-action="Index">Agendamentos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>